# Autogenerated by Astropy-affiliated package gausspy's setup.py on 2019-08-01 16:57:10 UTC
import datetime

version = "1.0"
githash = "4380a687526a29dd07cbb2dd8417c332a6a14cb8"


major = 1
minor = 0
bugfix = 0

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2019, 8, 1, 16, 57, 10)
debug = False

astropy_helpers_version = "4.0.dev1184"
